# .github/workflows/demo-reusable-deploy.yml
name: Demo Reusable Build Workflow

on:
  workflow_call:
    inputs:
      deploy-args:
        required: false
        type: string
    secrets:
      token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run build script
        run: |
          echo "Running build with ${{ inputs.deploy-args }}"
