# .github/workflows/demo-reusable-deploy.yml
name: Demo Reusable Build Workflow

on:
  workflow_call:
    inputs:
      github-event-name:
        required: false
        type: string
      deploy-args:
        required: false
        type: string
    secrets:
      token:
        required: true

jobs:
  info:
    uses: gekal-study-cicd/github-actions-reusable-templates/.github/workflows/demo-reusable-build.yml@main
    with:
      github-event-name: ${{ inputs.github-event-name }}
    secrets:
      token: ${{ secrets.token }}

  build:
    needs: [ info ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run deploy script
        run: |
          echo "Running deploy with ${{ inputs.deploy-args }}"
      - name: Say hello from deploy script
        run: |
          echo "Say hello from deploy script"
