# .github/workflows/demo-reusable-build.yml
name: Reusable Build Workflow

on:
  workflow_call:
    inputs:
      github-event-name:
        required: false
        type: string
      build-args:
        required: false
        type: string
    secrets:
      token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print github event name
        run: |
          echo "The github event name is: ${{ github.event_name }}"
      - name: Print github event name in inputs
        run: |
          echo "The github event name is: ${{ inputs.github-event-name }}"
      - name: Check if event name matched
        if: github.event_name == inputs.github-event-name
        run: |
          echo "Github event name matched."
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run build script
        run: |
          echo "Running build with ${{ inputs.build-args }}"
      - name: Say hello from build script
        run: |
          echo "Say hello from build script"
