# .github/workflows/main-workflow.yml
name: Main Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Print github event name
        run: |
          echo "The github event name is: ${{ github.event_name }}"

  build:
    needs: [ info ]
    uses: gekal-study-cicd/github-actions-reusable-templates/.github/workflows/demo-reusable-build.yml@feature/test
    with:
      github-event-name: pull_request
      build-args: "--build"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: [ build ]
    uses: gekal-study-cicd/github-actions-reusable-templates/.github/workflows/demo-reusable-deploy.yml@feature/test
    with:
      deploy-args: "--deploy"
      github-event-name: push
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
