# .github/workflows/demo-reusable-build.yml
name: Reusable Build Workflow

on:
  workflow_call:
    inputs:
      github-event-name:
        required: false
        type: string
      build-args:
        required: false
        type: string
    secrets:
      token:
        required: true

jobs:
#  build-info:
#    uses: ./.github/workflows/demo-reusable-build.yml
#    with:
#      github-event-name: ${{ inputs.github-event-name }}
#    secrets:
#      token: ${{ secrets.token }}

  build:
#    needs: [ build-info ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run build script
        run: |
          echo "Running build with ${{ inputs.build-args }}"
      - name: Say hello from build script
        run: |
          echo "Say hello from build script"
