# .github/workflows/demo-reusable-deploy.yml
name: Demo Reusable Build Workflow

on:
  workflow_call:
    inputs:
      deploy-args:
        required: false
        type: string
    secrets:
      token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run deploy script
        run: |
          echo "Running deploy with ${{ inputs.deploy-args }}"
      - name: Say hello from deploy script
        run: |
          echo "Say hello from deploy script"
