# .github/workflows/main-workflow.yml
name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Print github event name
        run: |
          echo "The github event name is: ${{ github.event_name }}"

  build:
    needs: [ info ]
    uses: ./.github/workflows/demo-reusable-build.yml
    with:
      build-args: "--build"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: [ build ]
    uses: ./.github/workflows/demo-reusable-deploy.yml
    with:
      deploy-args: "--deploy"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
