# .github/workflows/demo-reusable-info.yml
name: Reusable Info Workflow

on:
  workflow_call:
    inputs:
      github-event-name:
        required: false
        type: string
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

jobs:
  nested-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print github event name
        run: |
          echo "The github event name is: ${{ github.event_name }}"
      - name: Print github event name in inputs
        run: |
          echo "The github event name is: ${{ inputs.github-event-name }}"
      - name: Check if event name matched
        if: github.event_name == inputs.github-event-name
        run: |
          echo "Github event name matched."
